# Generated by Django 5.2 on 2025-04-12 21:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="city",
            field=models.CharField(
                blank=True, help_text="City of residence", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="club",
            field=models.CharField(
                blank=True, help_text="Current football club", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="country",
            field=models.CharField(
                blank=True,
                help_text="Current country of residence",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="state",
            field=models.CharField(
                blank=True,
                help_text="State/Province of residence",
                max_length=100,
                null=True,
            ),
        ),
    ]
