# Generated by Django 5.2 on 2025-04-12 22:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0003_player_fifa_profile_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("code", models.CharField(max_length=3, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "x_coordinate",
                    models.FloatField(
                        help_text="X coordinate on the football field (0-100)"
                    ),
                ),
                (
                    "y_coordinate",
                    models.FloatField(
                        help_text="Y coordinate on the football field (0-100)"
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, help_text="Is this a primary position?"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.RemoveField(
            model_name="player",
            name="position",
        ),
        migrations.AddField(
            model_name="player",
            name="positions",
            field=models.ManyToManyField(related_name="players", to="players.position"),
        ),
    ]
